variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  ECR_REGION: eu-west-1
  ECR_REGISTRY: 127206424101.dkr.ecr.eu-west-1.amazonaws.com/knmi
  AWS_CONFIG_FILE: ./aws-config
  REGION: eu-west-1
  TEMPLATE_FILE: cloudformation.yaml

services:
  - docker:dind

stages:
  - build
  - deploy-dev
  - deploy-acc
  - deploy-prd

.build:
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - apk add --no-cache py-pip
    - pip install awscli
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE/$REPOSITORY:$IMAGE_TAG" ${DOCKER_FILE_OPTION} .
    - docker push $CI_REGISTRY_IMAGE/$REPOSITORY:$IMAGE_TAG
    - "sh ecr.sh -r $REPOSITORY"
    - $(aws ecr get-login --no-include-email --region $ECR_REGION)
    - docker tag $CI_REGISTRY_IMAGE/$REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
    - docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
    - echo "${COMPONENT}ContainerImageTag=$IMAGE_TAG" >> $COMPONENT.cfn.properties
  artifacts:
    paths:
    - $COMPONENT.cfn.properties

.deploy:
  image: python:3
  before_script:
    - pip install awscli
  script:
    - echo "Environment=$ENVIRONMENT" >> deploy.cfn.properties
    - echo "EnvironmentSuffix=${CI_ENVIRONMENT_SLUG}" >> deploy.cfn.properties
    - cat *.cfn.properties
    - >-
      aws --profile $PROFILE cloudformation deploy --stack-name ${STACK_NAME} --template-file $TEMPLATE_FILE --capabilities
      CAPABILITY_NAMED_IAM --role-arn $ROLE_ARN --region $REGION --parameter-overrides $(cat *.cfn.properties)
      --no-fail-on-empty-changeset

build-server:
  extends: .build
  variables:
    IMAGE_TAG: "1.0.$CI_PIPELINE_ID"
    REPOSITORY: adaguc-server
    COMPONENT: AdagucServer
  only:
    - master

build-scanner:
  extends: .build
  variables:
    IMAGE_TAG: "1.0.$CI_PIPELINE_ID"
    REPOSITORY: adaguc-dataset-scanner
    COMPONENT: AdagucDatasetScanner
    DOCKER_FILE_OPTION: "-f dataset-scanner.Dockerfile"
  only:
    - master

build-server-dev:
  extends: .build
  variables:
    IMAGE_TAG: "dev-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"
    REPOSITORY: adaguc-server
    COMPONENT: AdagucServer
  only:
    - branches
  except:
    - master

build-scanner-dev:
  extends: .build
  variables:
    IMAGE_TAG: "dev-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"
    REPOSITORY: adaguc-dataset-scanner
    COMPONENT: AdagucDatasetScanner
    DOCKER_FILE_OPTION: "-f dataset-scanner.Dockerfile"
  only:
    - branches
  except:
    - master

.deploy-acc:
  extends: .deploy
  stage: deploy-acc
  variables:
    STACK_NAME: knmi-adaguc-server-acc
    IMAGE_TAG: "1.0.$CI_PIPELINE_ID"
    ENVIRONMENT: acc
    PROFILE: wlm-dta
    ROLE_ARN: arn:aws:iam::517047996289:role/knmi-cloudformation-stack-execution
  environment:
    name: $ENVIRONMENT
    url: http://adaguc-server.wlm.${ENVIRONMENT}.knmi.cloud
  only:
    - master
  when: manual

.deploy-prd:
  extends: .deploy
  stage: deploy-prd
  variables:
    STACK_NAME: knmi-adaguc-server
    IMAGE_TAG: "1.0.$CI_PIPELINE_ID"
    ENVIRONMENT: prd
    PROFILE: wlm-prd
    ROLE_ARN: arn:aws:iam::865722340438:role/knmi-cloudformation-stack-execution
  environment:
    name: $ENVIRONMENT
    url: http://adaguc-server.knmi.nl
  only:
    - master
  when: manual

deploy-dev:
  extends: .deploy
  stage: deploy-dev
  variables:
    STACK_NAME: knmi-adaguc-server-$CI_ENVIRONMENT_SLUG
    IMAGE_TAG: "dev-$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID"
    ENVIRONMENT: dev
    PROFILE: wlm-dta
    ROLE_ARN: arn:aws:iam::517047996289:role/knmi-cloudformation-stack-execution
  environment:
    name: $ENVIRONMENT/$CI_COMMIT_REF_SLUG
    url: http://adaguc-server-${CI_ENVIRONMENT_SLUG}.wlm.${ENVIRONMENT}.knmi.cloud
    on_stop: stop-dev
  only:
    - branches
  except:
    - master

stop-dev:
  image: python:3
  stage: deploy-dev
  variables:
    STACK_NAME: knmi-adaguc-server-$CI_ENVIRONMENT_SLUG
    ENVIRONMENT: dev
    PROFILE: wlm-dta
    ROLE_ARN: arn:aws:iam::517047996289:role/knmi-cloudformation-stack-execution
    # Manually run GIT_CHECKOUT to catch race condition on merge requests where branch is deleted
    # Workaround until https://gitlab.com/gitlab-org/gitlab-ce/issues/48361 is fixed
    GIT_CHECKOUT: 'false'
  environment:
    name: $ENVIRONMENT/$CI_COMMIT_REF_SLUG
    action: stop
  before_script:
    # Manually run git checkout, see above
    - pip install awscli
    - git checkout $CI_COMMIT_SHA || git checkout master
  script:
    - aws --profile $PROFILE cloudformation delete-stack --stack-name ${STACK_NAME} --role-arn $ROLE_ARN --region $REGION
  only:
    - branches
  except:
    - master
  when: manual
