version: '2'

services:
    adaguc-viewer:
        build: adaguc-viewer
        container_name: adaguc-viewer
        environment:
            - "LOCAL_ADAGUCSERVER_ADDR=${EXTERNALADDRESS}" # Should be same as adaguc-server's EXTERNALADDRESS
            - "REMOTE_ADAGUCSERVER_ADDR=http://adaguc-server:8080/" # Do not change this within the docker-compose environment
            - "ADAGUCSERVICES_AUTOWMS=${EXTERNALADDRESS}/adaguc-services/autowms?" 
        env_file:
          - .env
    adaguc-server:
        image: openearth/adaguc-server
        container_name: adaguc-server
        volumes:
            - ${ADAGUC_DATASET_DIR}/:/data/adaguc-datasets
            - ${ADAGUC_AUTOWMS_DIR}/:/data/adaguc-autowms
            - ${ADAGUC_DATA_DIR}/:/data/adaguc-data
            - ${ADAGUC_HOME}/adaguc-server-docker/adagucdb:/adaguc/adagucdb
            - ${ADAGUC_HOME}/adaguc-server-docker/adaguc-logs:/var/log/adaguc
        environment:
            - "EXTERNALADDRESS=${EXTERNALADDRESS}"
        env_file:
          - .env     
        ports:
          #- "80:80"
          - "8090:8080"          
    nginx:
        build: nginx-adaguc
        container_name: nginx-adaguc
        ports:
          #- "80:80"
          - "444:443"
        volumes:
          - ./letsencrypt:/etc/letsencrypt
          - ./cert:/cert
        restart: unless-stopped

        
#Run docker exec -i -t adaguc-server /adaguc/adaguc-server-updatedatasets.sh        
