version: '2'

services:
    adaguc-viewer:
        image: openearth/adaguc-viewer
        container_name: adaguc-viewer
        ports:
            - "8091:80"
    adaguc-server:
        image: openearth/adaguc-server
        container_name: adaguc-server
        ports:
            - "8090:8080"
        volumes:
            - $HOME/data/adaguc-datasets:/data/adaguc-datasets
            - $HOME/data/adaguc-autowms:/data/adaguc-autowms
        environment:
            - "EXTERNALADDRESS=http://127.0.0.1:8090/"
# cd ./adaguc-server/Docker
# To get a instance online:
#
# docker pull openearth/adaguc-viewer
# docker pull openearth/adaguc-server
# docker-compose up # In working directory and go to localhost:8090
# docker-compose down # To stop 
#
# Directories $HOME/data/adaguc-datasets and $HOME/data/adaguc-autowms will be created if they do not exist.
# Copy your NetCDF/GeoJSON/HDF5 to $HOME/data/adaguc-autowms
# Files are are accessible via
#   http://localhost:8090/adaguc-services/wms.cgi?source=testdata.nc&&service=WMS&request=GetCapabilities
#
# They can be visited in the adaguc-viewer via:
#   http://localhost:8091/adaguc-viewer/ by adding service http://localhost:8090/adaguc-services/wms.cgi?source=testdata.nc via "Add data"
# A direct link is:
#   http://localhost:8091/adaguc-viewer/?service=http%3A%2F%2Flocalhost%3A8090%2Fadaguc-services%2Fwms.cgi%3Fsource%3Dtestdata.nc
# Testdata can be found here:
#   http://opendap.knmi.nl/knmi/thredds/catalog/ADAGUC/catalog.html
# It is also possible to configure new datasets with custom styling and create aggregations over many files.
