version: '2'

services:
    adaguc-viewer:
        image: openearth/adaguc-viewer
        container_name: adaguc-viewer
        ports:
            - "8091:80"
        environment:
            - "LOCAL_ADAGUCSERVER_ADDR=http://localhost:8090/" # Should be same as adaguc-server's EXTERNALADDRESS
            - "REMOTE_ADAGUCSERVER_ADDR=http://adaguc-server:8080/"
    adaguc-server:
        image: openearth/adaguc-server
        container_name: adaguc-server
        ports:
            - "8090:8080"
        volumes:
            - $HOME/adaguc-server-docker/adaguc-datasetss:/data/adaguc-datasets
            - $HOME/adaguc-server-docker/adaguc-autowms:/data/adaguc-autowms
            - $HOME/adaguc-server-docker/adaguc-data:/data/adaguc-data
        environment:
            - "EXTERNALADDRESS=http://localhost:8090/"
# cd ./adaguc-server/Docker
# To get a instance online:
#
# docker pull openearth/adaguc-viewer
# docker pull openearth/adaguc-server
# docker-compose up # In working directory and go to http://localhost:8091/adaguc-viewer/ or http://localhost:8090/adaguc-services/wms.cgi? 
# mkdir -p $HOME/adaguc-server-docker/adaguc-data
# mkdir -p $HOME/adaguc-server-docker/adaguc-datasets
# mkdir -p $HOME/adaguc-server-docker/adaguc-autowms
# docker-compose down # To stop 
#
# Copy your NetCDF/GeoJSON/HDF5 to $HOME/adaguc-server-docker/adaguc-autowms
# Files are are accessible by linking them via the source= key. Filenames must be URLEncoded.
#   http://localhost:8090/adaguc-services/wms.cgi?source=testdata.nc&&service=WMS&request=GetCapabilities
#
# New files can be visualized in the adaguc-viewer via:
#   http://localhost:8091/adaguc-viewer/ by adding service http://localhost:8090/adaguc-services/wms.cgi?source=testdata.nc via "Add data"
# A direct link is:
#   http://localhost:8091/adaguc-viewer/?service=http%3A%2F%2Flocalhost%3A8090%2Fadaguc-services%2Fwms.cgi%3Fsource%3Dtestdata.nc
# Testdata can be found here:
#   http://opendap.knmi.nl/knmi/thredds/catalog/ADAGUC/catalog.html
# It is also possible to configure new datasets with custom styling and create aggregations over many files.
