version: '3.1'

services:
    adaguc-viewer:
        image: openearth/adaguc-viewer
        container_name: adaguc-viewer
        hostname: adaguc-viewer
        networks:
            - adaguc-network
        environment:
            - "LOCAL_ADAGUCSERVER_ADDR=${EXTERNALADDRESS}" # Should be same as adaguc-server's EXTERNALADDRESS
            - "REMOTE_ADAGUCSERVER_ADDR=http://adaguc-server:8080/" # Do not change this within the docker-compose environment
            - "ADAGUCSERVICES_AUTOWMS=${EXTERNALADDRESS}/adaguc-services/autowms?"
        env_file:
            - .env
        restart: unless-stopped
    adaguc-server:
        image: openearth/adaguc-server:ext-db
        container_name: my-adaguc-server
        hostname: my-adaguc-server
        volumes:
            - ${ADAGUC_DATASET_DIR}/:/data/adaguc-datasets
            - ${ADAGUC_AUTOWMS_DIR}/:/data/adaguc-autowms
            - ${ADAGUC_DATA_DIR}/:/data/adaguc-data
            - adaguc-server-compose-logs:/var/log/adaguc
            - /var/log/adaguc
            - /adaguc/security
        networks:
            - adaguc-network
        environment:
            - "EXTERNALADDRESS=${EXTERNALADDRESS}"
            - 'ADAGUC_DB="host=adaguc-db port=5432 user=adaguc password=adaguc dbname=adaguc"'
            - "ADAGUC_SERVICES_CONFIG=/adaguc/adaguc-services-config.xml"
        env_file:
            - .env
        restart: unless-stopped
    nginx:
        build: nginx-adaguc
        container_name: nginx-adaguc
        hostname: nginx-adacuc
        ports:
            - "${ADAGUC_PORT}:443"
        networks:
            - adaguc-network
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./cert:/cert
        restart: unless-stopped
    adaguc-db:
        image: postgres:9.6.12-alpine
        container_name: adaguc-db
        hostname: adaguc-db
        # Ensures containers running in the adaguc-network docker network can connect to the database, provided they use the
        # right credentials
        networks:
            - adaguc-network
        volumes:
            - adaguc-server-compose-adagucdb:/adaguc/adagucdb
        expose:
            - "5432"
        environment:
            - "POSTGRES_USER=adaguc"
            - "POSTGRES_PASSWORD=adaguc"
        restart: unless-stopped
volumes:
    adaguc-server-compose-adagucdb:
    adaguc-server-compose-logs:
networks:
    adaguc-network:

#Run 
# bash docker-compose-generate-env.sh -a ~/adaguc-server-docker/adaguc-autowms/ -d ~/adaguc-server-docker/adaguc-datasets/ -f ~/adaguc-server-docker/adaguc-data -p 443
# docker-compose pull
# docker-compose build
# docker-compose up -d
# wait 10 seconds for the services to start
# docker exec -it my-adaguc-server tail -f  /var/log/adaguc/adaguc-server.log
