"""
 This Python script runs the ADAGUC executable without an webserver. It can be used as example to run ADAGUC in your own environment from python.
 Created by Maarten Plieger - 20151104
"""

#URL without cascaded layers, for performance testing:
url="source=testdata.nc&SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=testdata&WIDTH=256&HEIGHT=256&CRS=EPSG%3A4326&BBOX=30,-30,75,30&STYLES=testdata%2Fnearest&FORMAT=image/png&TRANSPARENT=FALSE&"
# This is the url for the ADAGUCServer used to create maps, 
# with baselayer and overlay coming from http://geoservices.knmi.nl/ as configured in DefaultLayers.include.xml 
#  Use this URL instead to see pretty visualization 

#url="source=testdata.nc&SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=baselayer,testdata,overlay&WIDTH=1000&HEIGHT=750&CRS=EPSG%3A4326&BBOX=30,-30,75,30&STYLES=testdata%2Fnearest&FORMAT=image/png&TRANSPARENT=TRUE&showlegend=true&title=test&subtitle=test&showdims=true&showscalebar=true&shownortharrow=true"

# It is also possible to load date from remote opendap services 
#url="source=http://opendap.knmi.nl/knmi/thredds/dodsC/ADAGUC/testsets/projectedgrids/t2m.KNMI-2014.KNXT12.HCAST2.DD.nc.fixed.nc&SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=baselayer,t2m,grid10,overlay&WIDTH=1000&HEIGHT=750&CRS=EPSG%3A4326&BBOX=30,-30,75,30&STYLES=testdata%2Fnearest&FORMAT=image/png&TRANSPARENT=FALSE&showlegend=true&scalebar=true&showsdims=true&title=2+metre+temperature"

# A preview can be automatically generated by leaving out HEIGHT and BBOX
#url="source=http://opendap.knmi.nl/knmi/thredds/dodsC/ADAGUC/testsets/projectedgrids/t2m.KNMI-2014.KNXT12.HCAST2.DD.nc.fixed.nc&SERVICE=WMS&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=baselayer,t2m,grid10,overlay&WIDTH=500&CRS=EPSG%3A4326&STYLES=testdata%2Fnearest&FORMAT=image/png&TRANSPARENT=FALSE&showlegend=true&scalebar=true&showsdims=true&title=2+metre+temperature"


from adaguc.runAdaguc import runAdaguc

adagucInstance = runAdaguc()

img, logfile = adagucInstance.runGetMapUrl(url)

# adagucInstance.setConfiguration("./data/python/adaguc/adaguc-server-config-python.xml")
# logfile = adagucInstance.scanDataset("gsie")
# print("%s" % logfile)
# url = "dataset=gsie&&service=WMS&request=getmap&format=image/png&layers=interpolatedObs&width=400&CRS=EPSG:4326&STYLES=&EXCEPTIONS=INIMAGE&showlegend=true"
# img, logfile = adagucInstance.runGetMapUrl(url)

if img is not None:
  img.show()
  print(logfile)
else:
  print(logfile)



