name: Docker image build and publish

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-build-amd-only:
    name: Build Docker amd64 image (quick turnaround)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: github.repository == 'KNMI/adaguc-server'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: openearth/adaguc-server

      - name: Build and potentially push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          # ensure latest base image is used
          pull: true
          push: ${{ github.repository == 'KNMI/adaguc-server' }}
          tags: ${{ steps.meta.outputs.tags }}-03071218
          labels: ${{ steps.meta.outputs.labels }}
