name: Docker image CI

on:
  push:
    branches-ignore: [ $default-branch ]
  pull_request:
    branches-ignore: [ $default-branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
