name: Docker image build and publish

on:
  release:
    types: [published]
  push:
  pull_request:

jobs:
  push_to_registry:
    name: Build Docker image and potentially push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        if: github.repository == 'KNMI/adaguc-server' && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: openearth/adaguc-server

      - name: Build and potentially push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.repository == 'KNMI/adaguc-server' &&  github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
