name: Build Docker amd64 image

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker-build-and-publish:
    name: Build Docker amd64 image (quick turnaround)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and potentially push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          # ensure latest base image is used
          pull: true
          push: false
